### ISSUE TITLE
Order not recalculated when an order_with_respect_to field is modified

### ISSUE THREAD

**Issue by pablolmedorado** [django-ordered-model/django-ordered-model#121]
Hello everyone;

First, and before asking my question, **congratulations** on the work done.

I'm using the app to sort a set of polymorphic models.

The parent model uses **order_with_respect_to** (Subset Ordering) with **two** values and **order_class_path**.

Everything works great except editing an object, **either in the admin or through an api**.

When I edit one of the order_with_respect_to fields the order **is not recalculated**.

Any ideas? Thanks in advance.

**Comment by shuckc** [comment]
I think this duplicates #85 for the polymorphic case. Currently there's no special handling for updates to the order_with_respect_to field - we need to effectively delete the object's membership of the old ordering and add it to the new ordering.

**Comment by timhaley94** [comment]
@pablolmedorado, I ran into the same problem. I added my solution to the comments for #85.

**Comment by shuckc** [comment]
Hopefully resolved by #248
