### ISSUE TITLE
Record orders get reset

### ISSUE THREAD

**Issue by ACPK** [django-ordered-model/django-ordered-model#147]
When I push an item down one, it resets the order of multiple records randomly. It started happening after I deleted a few items.

**Comment by hvalee** [comment]
Hi also noticed this problem. 

When adding an ordered model object it does not set the new element to the last positions and sometimes shifts orders

**Comment by shuckc** [comment]
Please try the re-ordering tool  https://github.com/django-ordered-model/django-ordered-model#re-ordering-models to fix the problem, then a newer release.

**Comment by hvalee** [comment]
Opted to use another library, thank you anywaysSent from Android deviceEm 23/02/2022 12:51, Chris Shucksmith ***@***.***> escreveu:
Please try the re-ordering tool  https://github.com/django-ordered-model/django-ordered-model#re-ordering-models to fix the problem, then a newer release.
