### ISSUE TITLE
Deleting a model in an ordered list via cascade operation does not keep order

### ISSUE THREAD

**Issue by GeeWee** [django-ordered-model/django-ordered-model#182]
Assume we have two models.

```python
class Model1(models.Model)
   pass # Some model

class Model2(OrderedModel)
   model1 = models.ForeignKey(Model1, on_delete=models.CASCADE)
```
Running the following code will cause a gap in the positioning
```python
first_model1 = Model1.objects.create()
second_model1 Model1.objects.create()
first_model2 = Model2.objects.create(model1=first_model1) # given order 0
second_model2 = Model2.objects.create(model1=second_model1) # given order 1

first_model1.delete()
# This cascades and deletes first_model2, but the position of second_model2 is not updated
```

This is because Django does not call the `.delete` method on models for bulk or cascaded deletions: https://docs.djangoproject.com/en/dev/ref/models/querysets/#delete

It does however call the `post_delete` signal. I suggest we move the `.delete` method of the OrderedModel to a signal handler to solve this issue.

**Comment by imomaliev** [comment]
Hi @GeeWee, sounds like a design flaw in our part. I am currently busy and will have time to look into this next week. If you want to take this issue on you could provide PR with a fix

**Comment by GeeWee** [comment]
Hi @imomaliev - I have a PR with a test in #189

**Comment by Eraldo** [comment]
Any update on this? 😄
