### ISSUE TITLE
Recalculating order on changing FK on order_with_respect_to

### ISSUE THREAD

**Issue by Speedy1991** [django-ordered-model/django-ordered-model#198]
There is a bug, when the FK of a order_with_respect_to get's reasigned. Currently the order is always 0.

Maybe my other issue #196 is related and get's fixed with this patch too.

Example:
```
class StateMachine(OrderedModel):
  flow = models.ForeignKey(Flow, on_delete=models.PROTECT,  null=True, blank=True)
  order_with_respect_to = ("flow", )
```

Create some dummy data:
```
sm1 = StateMachine.objects.create(flow=flow1) -> order = 0
sm2 = StateMachine.objects.create(flow=flow2) -> order = 0
```

Now change `sm2.flow = sm1.flow` leads to:
```
sm1 => order = 0
sm2 => order = 0 (BUG expected 1)
```
Which leads to a broken database (up, down, etc is no more working)

The problem is in `OrderdModelBase.save`, there is only a check for if `order_field_name` value is None.
I currently fixed this with a monkey patch for the `__init__` and `save` methods on the `OrderdModelBase`:

```
    def __init__(self, *args, **kwargs):
        super(StateMachine, self).__init__(*args, **kwargs)
        self._original_order_with_respect_to_fks = {getattr(self, name) for name in self.order_with_respect_to}

    def save(self, *args, **kwargs):
        if getattr(self, self.order_field_name) is None or {getattr(self, name) for name in self.order_with_respect_to} != self._original_order_with_respect_to_fks:
            c = self.get_ordering_queryset().aggregate(Max(self.order_field_name)).get(self.order_field_name + '__max')
            setattr(self, self.order_field_name, 0 if c is None else c + 1)
        super(OrderedModelBase, self).save(*args, **kwargs)
        self._original_order_with_respect_to_fks = {getattr(self, name) for name in self.order_with_respect_to}
```

**Comment by Speedy1991** [comment]
oh i think it's a good idea to change
`{getattr(self, name) for name in self.order_with_respect_to}`
to
`{getattr(self, f"{name}_id") for name in self.order_with_respect_to}`
for less db lookups

**Comment by Eraldo** [comment]
Is there a workaround for this?
Even having a "fix order" action in the admin would already help.
Right now I can't even fix a broken order when I have 3 items all with order `0` for instance. :|

**Comment by Speedy1991** [comment]
You can run a custom `update` query - this doesn't run any django triggers/save methods

Depending on your model you can recalculate the order

**Comment by Eraldo** [comment]
Having a utility function to restore the order would be great.
Similar to how django-mptt does it (for tree structures): https://django-mptt.readthedocs.io/en/latest/models.html#rebuild

**Comment by shuckc** [comment]
I've been testing #188 which can sort out the resulting holes

**Comment by Eraldo** [comment]
The current version does of the management command is not able to handle the case where a model is ordered with respect to two fields. :|

**Comment by shuckc** [comment]
Since 3.7.x we now detect modifications to fields listed in `order_with_respect_to` and handle it properly. The administrative command (on master) now also handles manually re-ordering any inherited problematic datasets.
