### ISSUE TITLE
[Discussion] Move CI to github actions

### ISSUE THREAD

**Issue by imomaliev** [django-ordered-model/django-ordered-model#238]
@shuckc I think we should move CI to github actions, `django-ordered-model` development halted for almost a year because there were some issues with CI. Also recent policy changes which caused some controversy turned many projects away from it. 

What do you think?

**Comment by shuckc** [comment]
Agreed, plus Travis CI is moving anyway which I assume would require some work. We should also chat with @bfirsh see if we can get the package release process automated.

I've got to sort out an ordering issue #237 so will pick up some low-risk Issues along the way.

**Comment by shuckc** [comment]
I've just had to force push empty commits to trigger rebuilds on Travis due to what look like transient network failures. Probably better to switch to something with a retry button ;-)

**Comment by imomaliev** [comment]
@shuckc Package release already automated. Just create a git tag. And update `setup.py` and Travis will push to pypi

**Comment by imomaliev** [comment]
Here is example https://github.com/bfirsh/django-ordered-model/commit/900cc1577bb0e70288a833b5e101bf7ad2c828c2

**Comment by shuckc** [comment]
I'll have a go at moving CI to github actions as for example build #240 has passed on Travis and I'd like it to be mergeable, but the notification to github has been lost, so the test run is a write off.

**Comment by shuckc** [comment]
I've re-enabled branch protection using the github-actions names and added a test pypi key in the Secret. I will make a release via. the github mechanism and see if that triggers the Pypi test upload.

**Comment by shuckc** [comment]
Just made a release and after a few fixes the github action / pypi setup seems to be working nicely. See https://pypi.org/project/django-ordered-model/3.4.2/

I pushed a commit to set the `CHANGES` and `setup.py` values for the release 6f8fa541
Then I used the Github 'create release' button (per the attached screenshot) which did the tagging and kicked off the `distribute.yml` job to build and upload.

![screencapture-github-django-ordered-model-django-ordered-model-releases-new-2021-04-20-16_15_33](https://user-images.githubusercontent.com/1188286/115423460-c048fb80-a1f5-11eb-8aef-cd83bb59dc9c.png)

**Comment by imomaliev** [comment]
@shuckc Cool. Thank you!
