### ISSUE TITLE
Support for multiple ordering fields on the same model

### ISSUE THREAD

**Issue by browze** [django-ordered-model/django-ordered-model#249]
The way I read the docs, this package only supports setting one 'view' of ordering (i.e. one field per model) on the model itself.  The general use case for multiple fields would be different views (say of documents) where depending on the context, a different user defined order might be appropriate. 

Glancing at the code, it seems as though allowing a tuple to define order_field_name (where the first entry could be used as a 'default') would be fairly achievable... obviously only the default would be able to leverage default ordering using django's ordering Meta attribute.   Is this something you'd be interested in?  Do you forsee any particular difficulties?  I'm trying to decide whether to use this package or build something incrementally as my needs arise.

**Comment by browze** [comment]
Actually I'm leaning toward creating a separate 'order' model just to manage the order for each such 'view' - I could then use this package with those views... probably keeps it simpler/more explicit in the long run especially as these 'views' may be ordered with respect to other models too... they then begin to look like 'through' relations with the extra order field - and when I want the ordered view I query the model for that view and use 'select related' to get back the actual thing being ordered... sounds like a plan to me.  I'm guessing you'd endorse this approach over the idea of supporting multiple order fields per model?

**Comment by shuckc** [comment]
This sounds correct - separate the orderings into a simple classes each with a reference to the `Document`, ie. `DocumentViewOrdering(OrderedModel)` and `DocumentPrintOrdering(OrderedModel)` each with a 1:1 field to a `Document`. They can each be re-ordered independently.
