### ISSUE TITLE
Django Rest Framework serializer compatibility

### ISSUE THREAD

**Issue by Schwankenson** [django-ordered-model/django-ordered-model#251]
Hi,

thank you for this great django app! 

I needed to add/update OrderedModel instances with Django Rest framework, so I created this serializer. Maybe you want to implement it to the app (sorry, I\`m to busy to implement it by myself right now, but I thought it might be helpful to post the code):

    from rest_framework import serializers

    class OrderedModelSerializer(serializers.ModelSerializer):

        def update(self, instance, validated_data):
            order = None
            if "order" in validated_data:
                order = validated_data.pop("order")

            instance = super().update(instance, validated_data)

            if order is not None:
                instance.to(order)

            return instance
            

        def create(self, validated_data):
            order = None
            if "order" in validated_data:
                order = validated_data.pop("order")

            instance = super().create(validated_data)

            if order is not None:
                instance.to(order)

            return instance

**Comment by onlyphantom** [comment]
Hey @Schwankenson, are you able to shed some light as to how that would look like in a `bulk_create` situation?

```
class OrderedModelSerializer(serializers.ModelSerializer):
      pass

class BulkOrderedModelSerializer(serializers.ModelSerializer):
      orderedmodels = OrderedModelSerializer(many=True)
      class Meta:
          fields = ['questions']

      def create(self, validated_data):
          create_models = []
          for data in validated_data:
                 create_models.append(OrderedModelSerializer(**data))
          
           return OrderedModel.objects.bulk_create(create_models)
```

Been trying all kind of workarounds, and would appreciate just about any pointers.

**Comment by Schwankenson** [comment]
Oh, I had this bulk creation topic a few days ago - It`s no fun with the otherwise great django rest framework 😀:

I used this mixin in the ModelViewSet:

    class ModelViewsetWithBulkCreateMixin(object):

        def get_serializer(self, *args, **kwargs):
            """ if an array is passed, set serializer to many """
            if isinstance(kwargs.get('data', {}), list):
                kwargs['many'] = True
            return super().get_serializer(*args, **kwargs)
            
I used it with the OrderModelSerializer and it works. If field "order" is passed in a bulk creation request, it is used. If it is not passed, it is created from your app from 0-n. I did not try updating, only creation.

So maybe you just don`t need to implement a BulkOrderedModelSerializer

**Comment by onlyphantom** [comment]
Looks promising @Schwankenson , would you mind showing me an example of applying the custom mixin? Is it really just a decorator? Just about any code snippets to show me how to plug that mixin in would be such a great help.

Sorry -- first time using DRF and learning a lot of this as I go :(

**Comment by Schwankenson** [comment]
class MyModelViewset(ModelViewsetWithBulkCreateMixin, viewsets.ModelViewSet):
        queryset = MyModel.objects.all()
        serializer_class = MyModelSerializer # Instance or OrderedSerializer
    
That should be all, to make it work. You than just have to create a router like described in: 

https://www.django-rest-framework.org/api-guide/viewsets/#modelviewset

    router = DefaultRouter()
    router.register(r'my_model', MyModelViewset, basename='my_model')
    urlpatterns = router.urls

And put the urlpatterns to your urls, and you have a fully working, bulk working ordered REST API for your models :)

In my project it`s combined with  https://github.com/axnsan12/drf-yasg to have a Swagger/Open API schema- But this does not work with the bulk model out of the box, and I did not implement it. And there is a new version: https://github.com/tfranzel/drf-spectacular

**Comment by shuckc** [comment]
These examples look quite useful. Since we have no direct dependancy on DRF we probably wouldn't make them part of our test suite, although we could easily formalise these notes to another `README` file.

**Comment by joshuadavidthomas** [comment]
To add another example to the issue, I ended up modifying the initial `OrderedModelSerializer` provided by @Schwankenson to support the use of a custom ordering field, provided by `django-ordered-model` under the `order_field_name` Model attribute.

```python
from rest_framework import serializers


class OrderedModelSerializer(serializers.ModelSerializer):
    """
    A ModelSerializer that works in tandem with the `django-ordered-model`
    package to provide a serializer that can be used to update and create
    objects in a specific order.

    In the `django-ordered-model` package, a `models.PositiveIntegerField`
    field called `order` is used to store the order of the Model objects.
    This field can be customized by setting the `order_field_name` attribute
    on the Model class.

    This serializer will automatically use the correct field name for the
    ordering field, either the custom one specified by the `order_field_name`
    attribute on the Model class, or the default `order` field.

    This serializer will also automatically move the object to the correct
    order if the ordering field is passed in the validated data.
    """

    def get_order_field(self):
        """
        Return the field name for the ordering field from the Model.

        The `order_field_name` attribute is set on the Model class, and is
        required to be set in order for this serializer to work.

        Returns:
            str: The field name for the ordering field.
        """
        ModelClass = self.Meta.model  # pylint: disable=no-member,invalid-name

        order_field_name = getattr(ModelClass, "order_field_name")

        if not order_field_name:
            order_field_name = "order"

        return order_field_name

    def update(self, instance, validated_data):
        """
        Update the instance.

        If the `order_field_name` attribute is passed in the validated data,
        the instance will be moved to the specified order.

        Returns:
            Model: The updated instance.
        """
        order = None
        order_field = self.get_order_field()

        if order_field in validated_data:
            order = validated_data.pop(order_field)

        instance = super().update(instance, validated_data)

        if order is not None:
            instance.to(order)

        return instance

    def create(self, validated_data):
        """
        Create a new instance.

        If the `order_field_name` attribute is passed in the validated data,
        the instance will be created at the specified order.

        Returns:
            Model: The created instance.
        """
        order = None
        order_field = self.get_order_field()

        if order_field in validated_data:
            order = validated_data.pop(order_field)

        instance = super().create(validated_data)

        if order is not None:
            instance.to(order)

        return instance
```

**Comment by joshuadavidthomas** [comment]
After some testing, I've realized the if statement in `get_order_field` is unneeded. If you inherit from `OrderedModel`, `order_field_name` is set for you to 'order'. If you inherit from `OrderedModelBase`, you need to set it yourself, as outlined in this package.

Updated function:
```python
    def get_order_field(self):
        """
        Return the field name for the ordering field from the Model.

        If inheriting from `OrderedModelBase`, the `order_field_name` attribute
        must be set on the Model class, as detailed in the documentation for
        `django-ordered-model`.

        If inheriting from `OrderedModel`, the `order_field_name` attribute
        is not required, as the `django-ordered-model` package will automatically
        set the `order_field_name` attribute to 'order' on the Model class.

        Returns:
            str: The field name for the ordering field.

        Raises:
            AttributeError: If the `order_field_name` attribute is not set on
                the Model class.
        """
        ModelClass = self.Meta.model  # pylint: disable=no-member,invalid-name

        order_field_name = getattr(ModelClass, "order_field_name")

        if not order_field_name:
            raise AttributeError(
                "The `order_field_name` attribute must be set on the Model "
                "class to use the OrderedModelSerializer. Either inherit "
                "from OrderedModel (to use the default `order` field) or "
                "inherit from `OrderedModelBase` and set the `order_field_name` "
                f"attribute on the {ModelClass.__name__} Model class."
            )

        return order_field_name
```

**Comment by joshuadavidthomas** [comment]
After a bit more testing, I have yet another update. 

I needed to support using a different `order_field_name` than the one defined on the Model, e.g. my serializer actually returns a camelCased field name because that's what the frontend devs expect whereas on the Model it's snake_cased.

Hopefully someone else finds this useful.

```python
def get_order_field(self):
    """
    Return the field name for the ordering field.

    If inheriting from `OrderedModelBase`, the `order_field_name` attribute
    must be set on the Model class, as detailed in the documentation for
    `django-ordered-model`.

    If inheriting from `OrderedModel`, the `order_field_name` attribute
    is not required, as the `django-ordered-model` package will automatically
    set the `order_field_name` attribute to 'order' on the Model class.

    If the serializer sets a different name for the ordering field, e.g.
    a camelCase version of the field name, the `order_field_name` attribute
    must be set to the customized name on the serializer's Meta class.

    Example:
        # models.py
        from django.db import models
        from ordered_model.models import OrderedModelBase

        class OrderedModel(OrderedModelBase):
            custom_order = models.PositiveIntegerField(default=1)

            order_field_name = "custom_order"


        # serializers.py
        from rest_framework import serializers
        from path.to.project.serializers import OrderedModelSerializer

        class CustomNamedOrderedModelSerializer(OrderedModelSerializer):
            customOrder = serializers.PositiveIntegerField(source='custom_order')

            class Meta:
                model = OrderedModel
                order_field_name = 'customOrder'

    Returns:
        str: The field name for the ordering field.

    Raises:
        AttributeError: If the `order_field_name` attribute is not set,
            either on the Model class or on the serializer's Meta class.
    """
    order_field_name = getattr(self.Meta, "order_field_name")  # pylint: disable=no-member

    if not order_field_name:
        ModelClass = self.Meta.model  # pylint: disable=no-member,invalid-name
        order_field_name = getattr(ModelClass, "order_field_name")

    if not order_field_name:
        raise AttributeError(
            "The `order_field_name` attribute must be set to use the "
            "OrderedModelSerializer. Either inherit from OrderedModel "
            "(to use the default `order` field) or inherit from "
            "`OrderedModelBase` and set the `order_field_name` attribute "
            f"on the {ModelClass.__name__} Model class. If the ordering "
            "field is named differently, set the `order_field_name` "
            "attribute on the serializer's Meta class."
        )

    return order_field_name
```

**Comment by shuckc** [comment]
It does not look necessary to have `order_field_name` on the `Serializer`'s meta object.

From what I can see, if your serializers rename the field (by not including the original, and adding an `IntegerField(source='order')` field) by the time the data reaches `update(..., validated_data)`, the keys are already translated back to model field names.

e.g.

```
class RenamedItemSerializer(OrderedModelSerializer):
    renamedOrder = serializers.IntegerField(source='order')

    class Meta:
        model = CustomItem
        fields = ("pkid", "name", "renamedOrder")
        order_field_name = 'renamedOrder'

class RenamedItemViewSet(viewsets.ModelViewSet):
    queryset = CustomItem.objects.all()
    serializer_class = RenamedItemSerializer

router = routers.DefaultRouter()
...
router.register(r"renameditems", RenamedItemViewSet, basename='renameditem')
```

If I intercept within `OrderedModelSerializer.update()` by throwing an Exception I see:
```
class OrderedModelSerializer(...):
    ...
    def update(self, instance, validated_data):
        order = None
        order_field = self.get_order_field()
        raise Exception(f"moving {instance} to {order} from {validated_data} ordfield {order_field}")
```

Test case:

        # move b to top
        response = self.client.patch(
            reverse("renameditem-detail", kwargs={"pk": "b"}),
            {"renamedOrder": 0},
            format="json",
        )

    Exception: moving CustomItem object (b) to None from {'order': 0} ordfield renamedOrder
