### ISSUE TITLE
Use own querysets together with ordered model

### ISSUE THREAD

**Issue by eliezerp3** [django-ordered-model/django-ordered-model#259]
Hi. Thank you for this package. I have my own querysets I would like to use on my model. I made my own manager and inherited from OrderedModelManager but if I override get_queryset with my own queryset then I lose access to your queryset which breaks the package.

**Comment by imomaliev** [comment]
Hi, you need to inherit your queryset from https://github.com/django-ordered-model/django-ordered-model/blob/6e9a73711608e40f0beec7f405681ffb3fb69149/ordered_model/models.py#L14 `OrderedModelQuerySet`

**Comment by shuckc** [comment]
Improved documentation by merging #263
