### ISSUE TITLE
Use two managers in one model

### ISSUE THREAD

**Issue by darbre** [django-ordered-model/django-ordered-model#270]
Hi!

I have a Place model with subclasses Restaurant and Bar. I attached InheritanceManager from [django-model-utils](https://django-model-utils.readthedocs.io/en/4.2.0/managers.html#inheritancemanager) to Place to use the select_subclasses() method to get instances of the subclass.

```
from model_utils.managers import InheritanceManager


class Place(models.Model):
    # ...
    objects = InheritanceManager()

class Restaurant(Place):
    # ...

class Bar(Place):
    # ...
```
Everything worked fine. But now I want to set the order of the model Place.

```
...
objects = OrderedModelManager()
...
```
How to combine them?
Thanks.

**Comment by imomaliev** [comment]
You need to create new Manager class that inherits from both `InheritanceManager` and `OrderedModelManager`

```python
class PlaceManager(InheritanceManager, OrderedModelManager)
    ...
    
class Place(models.Model):
    # ...
    objects = PlaceManager()
```

**Comment by darbre** [comment]
I have tried this method. If I try to move the object in the admin, I got an error:

AttributeError at /admin/myapp/place/6/move-top/
'InheritanceQuerySet' object has no attribute 'filter_by_order_with_respect_to'

**Comment by imomaliev** [comment]
You need to overload to queryset as well. And this queryset should be subclass of OrderedModelQueryset

**Comment by darbre** [comment]
`objects = InheritanceManager.from_queryset(OrderedModelQuerySet)()`

error: AttributeError
'OrderedModelQuerySet' object has no attribute 'select_subclasses'

**Comment by imomaliev** [comment]
You should've created new QuerySet that inherits `OrderedModelQuerySet` and `InheritanceQuerySet` and then passed it to your new `PlaceManager`
