### ISSUE TITLE
Admin interface `move-up` action sometimes skips numbers

### ISSUE THREAD

**Issue by Archmonger** [django-ordered-model/django-ordered-model#276]
## Use Case
The main thing I need is a sortable `SpotlightCategory`, that have several sortable `AppPackage`s that exist within

I tried to modify the examples in the docs to fit my use case, but the sorting on my `SpotlightCategory` class seems to be broken.

## Issue Description

For `SpotlightCategory`: The `move-top`/`move-bottom` django-admin actions work, but the `move-up`/`move-down` action will sometimes randomly skip numbers.

For `SpotlightApp`: All move buttons work as expected.

 them.

### admin.py
```python
class SpotlightAppTabularInline(OrderedTabularInline):
    model = models.SpotlightApp
    readonly_fields = (
        "order",
        "move_up_down_links",
    )
    ordering = ("order",)
    extra = 1


@admin.register(models.SpotlightCategory)
class SpotlightCategories(OrderedInlineModelAdminMixin, OrderedModelAdmin):
    model = models.SpotlightCategory
    list_display = ("name", "order", "move_up_down_links")
    ordering = ("order",)
    inlines = (SpotlightAppTabularInline,)
```

### models.py
```python
class AppPackage(models.Model):
    def __str__(self):
        return str(self.name)

    uuid = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True
    )

    # General Info
    name = models.CharField(max_length=100)

class SpotlightCategory(OrderedModel):
    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = "Spotlight category"
        verbose_name_plural = "Spotlight categories"

    uuid = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True
    )

    name = models.CharField(max_length=50, unique=True)
    description = models.TextField(blank=True)
    apps = models.ManyToManyField(AppPackage, through="SpotlightApp")


class SpotlightApp(OrderedModel):
    """This model is used to create a many-to-many relationship between SpotlightCategory and AppPackage.
    This allows for the ordering of apps within a spotlight category."""

    category = models.ForeignKey(SpotlightCategory, on_delete=models.CASCADE)
    app = models.ForeignKey(AppPackage, on_delete=models.CASCADE)
    order_with_respect_to = "category"

    class Meta:
        ordering = ("category", "order")
```

**Comment by pandichef** [comment]
I'm getting the same issue

**Comment by shuckc** [comment]
Sort of. I will merge something and cut a release if a PR looks uncontroversial and might fix things. I have a project using this library, but it's a small dataset, seldom modified.

**Comment by pandichef** [comment]
> @shuckc Do you still maintain this package?

I ended up writing a baby version of the admin features that uses [order_with_respect_to](https://docs.djangoproject.com/en/4.1/ref/models/options/#order-with-respect-to).   It's not hard to do.  FWIW

**Comment by Archmonger** [comment]
> I ended up writing a baby version of the admin features that uses [order_with_respect_to](https://docs.djangoproject.com/en/4.1/ref/models/options/#order-with-respect-to). It's not hard to do. FWIW

Perhaps worth considering making a new python package that's a simplified version?

**Comment by pandichef** [comment]
> > I ended up writing a baby version of the admin features that uses [order_with_respect_to](https://docs.djangoproject.com/en/4.1/ref/models/options/#order-with-respect-to). It's not hard to do. FWIW
> 
> Perhaps worth considering making a new python package that's a simplified version?

yes, perhaps.  It's just a lot of work to maintain.  Also, I kind of feel like it should really be a pull request in Django core.  It feel like [order_with_respect_to](https://docs.djangoproject.com/en/4.1/ref/models/options/#order-with-respect-to) was started and never finished.

**Comment by Archmonger** [comment]
I got that warning when testing out #265 , and added in those ordering. 

I did not confirm whether that fixes the issue description though.

I'll test this weekend.

**Comment by Archmonger** [comment]
Tested, working as expected on #285 

Thank you!
