### ISSUE TITLE
OrderWithRespectToTestsManyToMany.test_down defined twice

### ISSUE THREAD

**Issue by ibaguio** [django-ordered-model/django-ordered-model#296]
https://github.com/django-ordered-model/django-ordered-model/blob/master/tests/tests.py#L741

and 

https://github.com/django-ordered-model/django-ordered-model/blob/master/tests/tests.py#L762

We might want to rename one or merge them?

**Comment by shuckc** [comment]
Good spot, looks like the first tests should be called `test_next` and `test_next_last`
