### ISSUE TITLE
(ordered_model.E001) OrderedModelBase subclass needs Meta.ordering specified check is required as an Error?

### ISSUE THREAD

**Issue by quevon24** [django-ordered-model/django-ordered-model#308]
Why this is an error and not a warning, and the ordering option is required? The library can not work without this option? 

It would be a good idea to make the initial ordering optional, since forcing the ordering hurts the performance of the database, this is more noticeable in applications with millions of records because is cheaper to execute MyModel.objects.all() than MyModel.objects.all().order_by('order')

Declaring ordering in Meta should be optional and not forced to `ordering = ("order",)`, i think `ordering = ()` should be an option

It's nice to have it as a default option in OrderedModel but it should be possible to disable the ordering

It seems to work correctly if you change this:

```
checks.Error(
                    "OrderedModelBase subclass needs Meta.ordering specified.",
                    hint="If you have overwritten Meta, try inheriting with Meta(OrderedModel.Meta).",
                    obj=str(cls.__qualname__),
                    id="ordered_model.E001",
                )
```

to this:
```

checks.Warning(
                    "OrderedModelBase subclass needs Meta.ordering specified.",
                    hint="If you have overwritten Meta, try inheriting with Meta(OrderedModel.Meta).",
                    obj=str(cls.__qualname__),
                    id="ordered_model.E001",
                )
```

**Comment by shuckc** [comment]
The library does not work *correctly* without specifying an argument. See for instance https://github.com/django-ordered-model/django-ordered-model/issues/276 . Catching the bad configuration is exactly the right thing to do.
