### ISSUE TITLE
`OrderedManyToMany` does not respect Django query cache

### ISSUE THREAD

**Issue by Archmonger** [django-ordered-model/django-ordered-model#318]
Original discussion: https://github.com/django-ordered-model/django-ordered-model/issues/277#issuecomment-1492873203

---

By default, Django query instances cache their results so that subsequent calls to the same object do not hit the database. This is a behavior we rely on [within `ReactPy-Django`](https://reactive-python.github.io/reactpy-django/latest/reference/hooks/#use-query) to maintain ORM compatibility.

However, `OrderedManyToMany` does not seem to respect that same caching behavior as Django's built-in model fields. For example...

```python
from django.db.models import prefetch_related_objects

categories = SpotlightCategory.objects.all()

# Initial run forces DB query execution to allow results to be stored in cache
for category in categories:
   # This should label the 'apps' field as a value that should be cached
   prefetch_related_objects([category], 'apps')

   print(category.name)  # Call attribute to force `Model` to execute DB queries
   print(category.apps.get_queryset().all())  # Call the `QuerySet` to execute DB queries

# Second run, everything should already be stored in cache
for category in categories:
   print(category.name)  # This works as expected (the result is cached)
   print(category.apps.get_queryset().all())  # This causes a new query to be performed. It should have been cached.
```

**Comment by shuckc** [comment]
As I said on #277, I'm no expert on this, but I would have expected two lots of queries when you are calling `get_queryset()`  twice. I believe the cache is kept within the query-set, which you are not re-using.

Perhaps open a PR that adds a test case of a non-ordered model, that shows using `assertNumQueries` that we are wrong?
Or can you link me to Django docs or test cases that demonstrate your belief to be true?

**Comment by Archmonger** [comment]
Since everything about the Django ORM [is lazy](https://docs.djangoproject.com/en/5.0/topics/db/queries/#querysets-are-lazy), models and querysets have a built-in caching mechanisms. Otherwise, [this logic](https://github.com/reactive-python/reactpy-django/blob/9b36b6d371c611ceaa1f51815b87ddc43ead6804/src/reactpy_django/utils.py#L281-L340) we rely on have never worked.

Our tests prove that calling the results of `get_queryset()` is cached as well.

**Comment by shuckc** [comment]
Lazy evaluation is nothing to do with caching. 
Here is Django documentation specifying that two different QuerySets (ie. as returned by `get_queryset()`) do not share a cache.  https://docs.djangoproject.com/en/5.0/topics/db/queries/#caching-and-querysets

> Each [QuerySet](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#django.db.models.query.QuerySet) contains a cache to minimize database access. Understanding how it works will allow you to write the most efficient code.
> In a newly created [QuerySet](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#django.db.models.query.QuerySet), the cache is empty. The first time a [QuerySet](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#django.db.models.query.QuerySet) is evaluated – and, hence, a database query happens – Django saves the query results in the [QuerySet](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#django.db.models.query.QuerySet)’s cache and returns the results that have been explicitly requested (e.g., the next element, if the [QuerySet](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#django.db.models.query.QuerySet) is being iterated over). 
> Subsequent evaluations of the [QuerySet](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#django.db.models.query.QuerySet) reuse the cached results.
>
> Keep this caching behavior in mind, because it may bite you if you don’t use your [QuerySet](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#django.db.models.query.QuerySet)s correctly. For example, the following will create two [QuerySet](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#django.db.models.query.QuerySet)s, evaluate them, and throw them away:
> ```
>>> print([e.headline for e in Entry.objects.all()])
>>> print([e.pub_date for e in Entry.objects.all()])
> ```
> That means the same database query will be executed twice, effectively doubling your database load. Also, there’s a possibility the two lists may not include the same database records, because an Entry may have been added or deleted in the split second between the two requests.
> 
> To avoid this problem, save the [QuerySet](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#django.db.models.query.QuerySet) and reuse it:
>
> ```
>>> queryset = Entry.objects.all()
>>> print([p.headline for p in queryset])  # Evaluate the query set.
>>> print([p.pub_date for p in queryset])  # Reuse the cache from the evaluation.
> ```
