### ISSUE TITLE
[QUESTION] New release of 3.7.5 or 3.8 at PyPI

### ISSUE THREAD

**Issue by DmytroLitvinov** [django-ordered-model/django-ordered-model#323]
Hi there,
_First, want to say thanks for that great library 👍 Use it for my projects at work._ 

And regarding the issue submitted wanted to ask about release which has personally for me needed feature like `fields. OrderedManyToManyField` (more details [here](https://github.com/django-ordered-model/django-ordered-model/commit/8e5d6413fd6183ba82be7131e4d45e4dbb0dfc70)).

I see [there were no releases](https://github.com/django-ordered-model/django-ordered-model/blob/master/CHANGES.md) from 2023-03-17 so it would also give some "fresh" update on the library. And according to Unreleased paragraph, there are a lot of significant changes.

P.S. I know that I can install package directly from `master` but my point of view also is that keep that as a release with changes at PyPI even if it is minor changes so to keep it up to date that's why raised that issue at GitHub 😊

**Comment by shuckc** [comment]
The blocker for a new release is https://github.com/django-ordered-model/django-ordered-model/pull/295#issuecomment-1930368591 - without it there is a performance issue in some use cases, and it's not straightforward.

**Comment by shuckc** [comment]
I've release `3.8.0-alpha`, which includes everything from master, and gives us chance to get some wider testing of what we have so far.
