### ISSUE TITLE
[QUESTION] Order with respect to for non FK fields

### ISSUE THREAD

**Issue by QuantumaStelata** [django-ordered-model/django-ordered-model#331]
Hi there,
First, want to say thanks for that great library 🤝

And regarding the presented question, I wanted to ask if there are any locks for implementing the use of order_with_respect_to for non foreign fields? In my projects, I often use Integer/Char fields with Integer/Text choices and would like to bind sorting to these fields, but I can't do this because of the limitation and the `ordered_model.E005` error. Or perhaps you have an explanation why such fields should not be used for sorting?

Thanks in advance!

**Comment by shuckc** [comment]
It's merged but not yet released - from the CHANGELOG 

```
Relax check that order_with_respect_to entries final element must be a ForeignKey - it can be any Field instance (#298)
```

**Comment by DmytroLitvinov** [comment]
Linking PR https://github.com/django-ordered-model/django-ordered-model/pull/317 to issue :)
