### ISSUE TITLE
Is this package compatible with Django 5.0+?

### ISSUE THREAD

**Issue by semihsezer** [django-ordered-model/django-ordered-model#332]
I didn't see it explicitly mentioned in compatibility notes so I wanted to clarify if there are any known limitations.
Thanks in advance!

**Comment by semihsezer** [comment]
Thanks for your response. It seems to work fine in Django 5. I deployed it, no issues so far.
I have a simple use case with `order_with_respect_to = "user"`.

**Comment by shuckc** [comment]
All tests pass, I've also added a python 3.12 builder which is also green.
